/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    factories: Factory;
    smd_line_name: SmdLineName;
    SmdQuestions: SmdQuestion;
    pmd_lines: PmdLine;
    PMDQuestions: PMDQuestion;
    eng_lines: EngLine;
    ENGQuestions: ENGQuestion;
    FMD_Lines: FMD_Line;
    FMDQuestions: FMDQuestion;
    Engineering_Quality_Inspection: Engineering_Quality_Inspection;
    FMD_Quality_Inspection: FMD_Quality_Inspection;
    PMD_Quality_Inspection: PMD_Quality_Inspection;
    SMD_Quality_Inspection: SMD_Quality_Inspection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    factories: FactoriesSelect<false> | FactoriesSelect<true>;
    smd_line_name: SmdLineNameSelect<false> | SmdLineNameSelect<true>;
    SmdQuestions: SmdQuestionsSelect<false> | SmdQuestionsSelect<true>;
    pmd_lines: PmdLinesSelect<false> | PmdLinesSelect<true>;
    PMDQuestions: PMDQuestionsSelect<false> | PMDQuestionsSelect<true>;
    eng_lines: EngLinesSelect<false> | EngLinesSelect<true>;
    ENGQuestions: ENGQuestionsSelect<false> | ENGQuestionsSelect<true>;
    FMD_Lines: FMD_LinesSelect<false> | FMD_LinesSelect<true>;
    FMDQuestions: FMDQuestionsSelect<false> | FMDQuestionsSelect<true>;
    Engineering_Quality_Inspection: Engineering_Quality_InspectionSelect<false> | Engineering_Quality_InspectionSelect<true>;
    FMD_Quality_Inspection: FMD_Quality_InspectionSelect<false> | FMD_Quality_InspectionSelect<true>;
    PMD_Quality_Inspection: PMD_Quality_InspectionSelect<false> | PMD_Quality_InspectionSelect<true>;
    SMD_Quality_Inspection: SMD_Quality_InspectionSelect<false> | SMD_Quality_InspectionSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Create user as and admin,data clerk, operator and link the user to a factory
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role?: ('superadmin' | 'operator' | 'clerk') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Factories in BAT
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factories".
 */
export interface Factory {
  id: string;
  factory_name: string;
  country: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lines in SMD
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smd_line_name".
 */
export interface SmdLineName {
  id: string;
  smd_line_name: string;
  user?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SMD Safety Inspection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SmdQuestions".
 */
export interface SmdQuestion {
  id: string;
  user?: (string | User)[] | null;
  Line: (string | SmdLineName)[];
  Q1: 'yes' | 'no';
  Q2: 'yes' | 'no';
  Q3: 'yes' | 'no';
  Q4: 'yes' | 'no';
  Q5: 'yes' | 'no';
  Q6: 'yes' | 'no';
  Q7: 'yes' | 'no';
  Q8: 'yes' | 'no';
  Q9: 'yes' | 'no';
  Q10: 'yes' | 'no';
  Q11: 'yes' | 'no';
  Q12: 'yes' | 'no';
  Q13: 'yes' | 'no';
  Q14: 'yes' | 'no';
  Q15: 'yes' | 'no';
  Q16: 'yes' | 'no';
  Q17: 'yes' | 'no';
  Q18: 'yes' | 'no';
  Q19: 'yes' | 'no';
  Q20: 'yes' | 'no';
  Q21: 'yes' | 'no';
  Q22: 'yes' | 'no';
  Q23: 'yes' | 'no';
  Q24: 'yes' | 'no';
  Q25: 'yes' | 'no';
  Q26: 'yes' | 'no';
  Q27: 'yes' | 'no';
  Q28: 'yes' | 'no';
  Trigger?: string | null;
  reasonForScore?: string | null;
  inspectorNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * lines in PMD
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pmd_lines".
 */
export interface PmdLine {
  id: string;
  pmd_lines: string;
  user?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PMD Safety Inspection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PMDQuestions".
 */
export interface PMDQuestion {
  id: string;
  user?: (string | User)[] | null;
  Line: (string | PmdLine)[];
  Q1: 'yes' | 'no';
  Q2: 'yes' | 'no';
  Q3: 'yes' | 'no';
  Q4: 'yes' | 'no';
  Q5: 'yes' | 'no';
  Q6: 'yes' | 'no';
  Q7: 'yes' | 'no';
  Q8: 'yes' | 'no';
  Q9: 'yes' | 'no';
  Q10: 'yes' | 'no';
  Q11: 'yes' | 'no';
  Q12: 'yes' | 'no';
  Q13: 'yes' | 'no';
  Q14: 'yes' | 'no';
  Q15: 'yes' | 'no';
  Q16: 'yes' | 'no';
  Q17: 'yes' | 'no';
  Q18: 'yes' | 'no';
  Q19: 'yes' | 'no';
  Q20: 'yes' | 'no';
  Q21: 'yes' | 'no';
  Q22: 'yes' | 'no';
  Q23: 'yes' | 'no';
  Q24: 'yes' | 'no';
  Q25: 'yes' | 'no';
  Q26: 'yes' | 'no';
  Q27: 'yes' | 'no';
  Q28: 'yes' | 'no';
  Trigger?: string | null;
  reasonForScore?: string | null;
  inspectorNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * lines in Engineering
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eng_lines".
 */
export interface EngLine {
  id: string;
  eng_lines: string;
  user?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ENG Safety Inspection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ENGQuestions".
 */
export interface ENGQuestion {
  id: string;
  user?: (string | User)[] | null;
  Line: (string | EngLine)[];
  Q1: 'yes' | 'no';
  Q2: 'yes' | 'no';
  Q3: 'yes' | 'no';
  Q4: 'yes' | 'no';
  Q5: 'yes' | 'no';
  Q6: 'yes' | 'no';
  Q7: 'yes' | 'no';
  Q8: 'yes' | 'no';
  Q9: 'yes' | 'no';
  Q10: 'yes' | 'no';
  Q11: 'yes' | 'no';
  Q12: 'yes' | 'no';
  Q13: 'yes' | 'no';
  Q14: 'yes' | 'no';
  Q15: 'yes' | 'no';
  Q16: 'yes' | 'no';
  Q17: 'yes' | 'no';
  Q18: 'yes' | 'no';
  Q19: 'yes' | 'no';
  Q20: 'yes' | 'no';
  Q21: 'yes' | 'no';
  Q22: 'yes' | 'no';
  Q23: 'yes' | 'no';
  Q24: 'yes' | 'no';
  Q25: 'yes' | 'no';
  Q26: 'yes' | 'no';
  Q27: 'yes' | 'no';
  Q28: 'yes' | 'no';
  Trigger?: string | null;
  reasonForScore?: string | null;
  inspectorNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * lines in FMD
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FMD_Lines".
 */
export interface FMD_Line {
  id: string;
  FMD_Lines: string;
  user?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * FMD Safety Inspection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FMDQuestions".
 */
export interface FMDQuestion {
  id: string;
  user?: (string | User)[] | null;
  Line: (string | FMD_Line)[];
  Q1: 'yes' | 'no';
  Q2: 'yes' | 'no';
  Q3: 'yes' | 'no';
  Q4: 'yes' | 'no';
  Q5: 'yes' | 'no';
  Q6: 'yes' | 'no';
  Q7: 'yes' | 'no';
  Q8: 'yes' | 'no';
  Q9: 'yes' | 'no';
  Q10: 'yes' | 'no';
  Q11: 'yes' | 'no';
  Q12: 'yes' | 'no';
  Q13: 'yes' | 'no';
  Q14: 'yes' | 'no';
  Q15: 'yes' | 'no';
  Q16: 'yes' | 'no';
  Q17: 'yes' | 'no';
  Q18: 'yes' | 'no';
  Q19: 'yes' | 'no';
  Q20: 'yes' | 'no';
  Q21: 'yes' | 'no';
  Q22: 'yes' | 'no';
  Q23: 'yes' | 'no';
  Q24: 'yes' | 'no';
  Q25: 'yes' | 'no';
  Q26: 'yes' | 'no';
  Q27: 'yes' | 'no';
  Q28: 'yes' | 'no';
  Trigger?: string | null;
  reasonForScore?: string | null;
  inspectorNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Engineering Quality Inspection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Engineering_Quality_Inspection".
 */
export interface Engineering_Quality_Inspection {
  id: string;
  user?: (string | User)[] | null;
  Line: (string | EngLine)[];
  Q1: 'yes' | 'no';
  Q2: 'yes' | 'no';
  Q3: 'yes' | 'no';
  Q4: 'yes' | 'no';
  Q5: 'yes' | 'no';
  Q6: 'yes' | 'no';
  Q7: 'yes' | 'no';
  Q8: 'yes' | 'no';
  Trigger?: string | null;
  reasonForScore?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * FMD Quality Inspection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FMD_Quality_Inspection".
 */
export interface FMD_Quality_Inspection {
  id: string;
  user?: (string | User)[] | null;
  Line: (string | FMD_Line)[];
  Q1: 'yes' | 'no';
  Q2: 'yes' | 'no';
  Q3: 'yes' | 'no';
  Q4: 'yes' | 'no';
  Q5: 'yes' | 'no';
  Q6: 'yes' | 'no';
  Q7: 'yes' | 'no';
  Q8: 'yes' | 'no';
  Trigger?: string | null;
  reasonForScore?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PMD Quality Inspection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PMD_Quality_Inspection".
 */
export interface PMD_Quality_Inspection {
  id: string;
  user?: (string | User)[] | null;
  Line: (string | PmdLine)[];
  Q1: 'yes' | 'no';
  Q2: 'yes' | 'no';
  Q3: 'yes' | 'no';
  Q4: 'yes' | 'no';
  Q5: 'yes' | 'no';
  Q6: 'yes' | 'no';
  Q7: 'yes' | 'no';
  Q8: 'yes' | 'no';
  Trigger?: string | null;
  reasonForScore?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SMD Quality Inspection
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SMD_Quality_Inspection".
 */
export interface SMD_Quality_Inspection {
  id: string;
  user?: (string | User)[] | null;
  Line: (string | SmdLineName)[];
  Q1: 'yes' | 'no';
  Q2: 'yes' | 'no';
  Q3: 'yes' | 'no';
  Q4: 'yes' | 'no';
  Q5: 'yes' | 'no';
  Q6: 'yes' | 'no';
  Q7: 'yes' | 'no';
  Q8: 'yes' | 'no';
  Trigger?: string | null;
  reasonForScore?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'factories';
        value: string | Factory;
      } | null)
    | ({
        relationTo: 'smd_line_name';
        value: string | SmdLineName;
      } | null)
    | ({
        relationTo: 'SmdQuestions';
        value: string | SmdQuestion;
      } | null)
    | ({
        relationTo: 'pmd_lines';
        value: string | PmdLine;
      } | null)
    | ({
        relationTo: 'PMDQuestions';
        value: string | PMDQuestion;
      } | null)
    | ({
        relationTo: 'eng_lines';
        value: string | EngLine;
      } | null)
    | ({
        relationTo: 'ENGQuestions';
        value: string | ENGQuestion;
      } | null)
    | ({
        relationTo: 'FMD_Lines';
        value: string | FMD_Line;
      } | null)
    | ({
        relationTo: 'FMDQuestions';
        value: string | FMDQuestion;
      } | null)
    | ({
        relationTo: 'Engineering_Quality_Inspection';
        value: string | Engineering_Quality_Inspection;
      } | null)
    | ({
        relationTo: 'FMD_Quality_Inspection';
        value: string | FMD_Quality_Inspection;
      } | null)
    | ({
        relationTo: 'PMD_Quality_Inspection';
        value: string | PMD_Quality_Inspection;
      } | null)
    | ({
        relationTo: 'SMD_Quality_Inspection';
        value: string | SMD_Quality_Inspection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factories_select".
 */
export interface FactoriesSelect<T extends boolean = true> {
  factory_name?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smd_line_name_select".
 */
export interface SmdLineNameSelect<T extends boolean = true> {
  smd_line_name?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SmdQuestions_select".
 */
export interface SmdQuestionsSelect<T extends boolean = true> {
  user?: T;
  Line?: T;
  Q1?: T;
  Q2?: T;
  Q3?: T;
  Q4?: T;
  Q5?: T;
  Q6?: T;
  Q7?: T;
  Q8?: T;
  Q9?: T;
  Q10?: T;
  Q11?: T;
  Q12?: T;
  Q13?: T;
  Q14?: T;
  Q15?: T;
  Q16?: T;
  Q17?: T;
  Q18?: T;
  Q19?: T;
  Q20?: T;
  Q21?: T;
  Q22?: T;
  Q23?: T;
  Q24?: T;
  Q25?: T;
  Q26?: T;
  Q27?: T;
  Q28?: T;
  Trigger?: T;
  reasonForScore?: T;
  inspectorNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pmd_lines_select".
 */
export interface PmdLinesSelect<T extends boolean = true> {
  pmd_lines?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PMDQuestions_select".
 */
export interface PMDQuestionsSelect<T extends boolean = true> {
  user?: T;
  Line?: T;
  Q1?: T;
  Q2?: T;
  Q3?: T;
  Q4?: T;
  Q5?: T;
  Q6?: T;
  Q7?: T;
  Q8?: T;
  Q9?: T;
  Q10?: T;
  Q11?: T;
  Q12?: T;
  Q13?: T;
  Q14?: T;
  Q15?: T;
  Q16?: T;
  Q17?: T;
  Q18?: T;
  Q19?: T;
  Q20?: T;
  Q21?: T;
  Q22?: T;
  Q23?: T;
  Q24?: T;
  Q25?: T;
  Q26?: T;
  Q27?: T;
  Q28?: T;
  Trigger?: T;
  reasonForScore?: T;
  inspectorNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eng_lines_select".
 */
export interface EngLinesSelect<T extends boolean = true> {
  eng_lines?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ENGQuestions_select".
 */
export interface ENGQuestionsSelect<T extends boolean = true> {
  user?: T;
  Line?: T;
  Q1?: T;
  Q2?: T;
  Q3?: T;
  Q4?: T;
  Q5?: T;
  Q6?: T;
  Q7?: T;
  Q8?: T;
  Q9?: T;
  Q10?: T;
  Q11?: T;
  Q12?: T;
  Q13?: T;
  Q14?: T;
  Q15?: T;
  Q16?: T;
  Q17?: T;
  Q18?: T;
  Q19?: T;
  Q20?: T;
  Q21?: T;
  Q22?: T;
  Q23?: T;
  Q24?: T;
  Q25?: T;
  Q26?: T;
  Q27?: T;
  Q28?: T;
  Trigger?: T;
  reasonForScore?: T;
  inspectorNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FMD_Lines_select".
 */
export interface FMD_LinesSelect<T extends boolean = true> {
  FMD_Lines?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FMDQuestions_select".
 */
export interface FMDQuestionsSelect<T extends boolean = true> {
  user?: T;
  Line?: T;
  Q1?: T;
  Q2?: T;
  Q3?: T;
  Q4?: T;
  Q5?: T;
  Q6?: T;
  Q7?: T;
  Q8?: T;
  Q9?: T;
  Q10?: T;
  Q11?: T;
  Q12?: T;
  Q13?: T;
  Q14?: T;
  Q15?: T;
  Q16?: T;
  Q17?: T;
  Q18?: T;
  Q19?: T;
  Q20?: T;
  Q21?: T;
  Q22?: T;
  Q23?: T;
  Q24?: T;
  Q25?: T;
  Q26?: T;
  Q27?: T;
  Q28?: T;
  Trigger?: T;
  reasonForScore?: T;
  inspectorNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Engineering_Quality_Inspection_select".
 */
export interface Engineering_Quality_InspectionSelect<T extends boolean = true> {
  user?: T;
  Line?: T;
  Q1?: T;
  Q2?: T;
  Q3?: T;
  Q4?: T;
  Q5?: T;
  Q6?: T;
  Q7?: T;
  Q8?: T;
  Trigger?: T;
  reasonForScore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FMD_Quality_Inspection_select".
 */
export interface FMD_Quality_InspectionSelect<T extends boolean = true> {
  user?: T;
  Line?: T;
  Q1?: T;
  Q2?: T;
  Q3?: T;
  Q4?: T;
  Q5?: T;
  Q6?: T;
  Q7?: T;
  Q8?: T;
  Trigger?: T;
  reasonForScore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PMD_Quality_Inspection_select".
 */
export interface PMD_Quality_InspectionSelect<T extends boolean = true> {
  user?: T;
  Line?: T;
  Q1?: T;
  Q2?: T;
  Q3?: T;
  Q4?: T;
  Q5?: T;
  Q6?: T;
  Q7?: T;
  Q8?: T;
  Trigger?: T;
  reasonForScore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SMD_Quality_Inspection_select".
 */
export interface SMD_Quality_InspectionSelect<T extends boolean = true> {
  user?: T;
  Line?: T;
  Q1?: T;
  Q2?: T;
  Q3?: T;
  Q4?: T;
  Q5?: T;
  Q6?: T;
  Q7?: T;
  Q8?: T;
  Trigger?: T;
  reasonForScore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}